# Generated by Django 6.0.6 on 2026-08-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Введите ID чата Телеграм",
                max_length=100,
                null=True,
                verbose_name="ID Telegram",
            ),
        ),
    ]
