# Generated by Django 6.0.6 on 2026-09-03 15:37

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_tg_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tg_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Введите ID чата Телеграм', null=True, validators=[django.core.validators.MinValueValidator(-9223372036854775808, message='Слишком маленькое или некорректное число.'), django.core.validators.MaxValueValidator(9223372036854775807, message='Введен слишком длинный ID.'), users.models.validate_telegram_id], verbose_name='ID Telegram'),
        ),
    ]
