# Generated by Django 6.0.6 on 2026-09-06 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_tg_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('BASE', 'Базовый'), ('STANDARD', 'Стандартный'), ('PREMIUM', 'Премиум')], default='BASE', max_length=15, verbose_name='Тарифный план')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания подписки')),
                ('max_tasks', models.PositiveIntegerField(blank=True, default=50, verbose_name='Максимальное количество задач')),
                ('max_bookmarks', models.PositiveIntegerField(blank=True, default=5, verbose_name='Максимальное количество закладок')),
                ('is_archive', models.BooleanField(default=False, verbose_name='Флаг архивной подписки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_plan', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
            },
        ),
    ]
