# Generated by Django 6.0.6 on 2026-09-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tariffplans'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Получать уведомления по электронной почте', verbose_name='Уведомления по email'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_notifications',
            field=models.BooleanField(default=False, help_text='Получать уведомления в Telegram', verbose_name='Уведомления в Telegram'),
        ),
        migrations.AlterField(
            model_name='tariffplans',
            name='max_tasks',
            field=models.PositiveIntegerField(blank=True, default=50, verbose_name='Макс. количество задач на ОДНУ закладку'),
        ),
    ]
