# Generated by Django 6.0.6 on 2026-08-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0004_alter_bookmark_options_rename_name_bookmark_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_notified",
            field=models.BooleanField(
                default=False,
                help_text="Флаг контроля, чтобы не отправлять пуш повторно",
                verbose_name="Уведомление отправлено",
            ),
        ),
    ]
