# Generated by Django 6.0.6 on 2026-08-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0005_task_is_notified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status_flag",
            field=models.IntegerField(
                choices=[
                    (0, "Создана"),
                    (1, "В работе"),
                    (2, "Выполнена"),
                    (3, "Просрочена"),
                ],
                default=0,
                verbose_name="Признак управления",
            ),
        ),
    ]
