# Generated by Django 6.0.6 on 2026-08-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0006_alter_task_status_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="periodicity",
            field=models.DurationField(
                blank=True,
                default=None,
                help_text="Введите период повторения",
                null=True,
                verbose_name="Периодичность повторения",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="reminder_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Время напоминания"
            ),
        ),
    ]
