# Generated by Django 6.0.6 on 2026-08-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0007_task_periodicity_alter_task_reminder_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="periodicity",
        ),
        migrations.AddField(
            model_name="task",
            name="periodicity_unit",
            field=models.CharField(
                choices=[
                    ("none", "Не повторять"),
                    ("minutes", "Минут"),
                    ("hours", "Часов"),
                    ("days", "Дней"),
                    ("weeks", "Недель"),
                    ("months", "Месяцев"),
                    ("years", "Лет"),
                ],
                default="none",
                max_length=10,
                verbose_name="Единица времени",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="periodicity_value",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Значение периода"
            ),
        ),
    ]
