# Generated by Django 6.0.6 on 2026-09-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0008_remove_task_periodicity_task_periodicity_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='execution_log',
            field=models.TextField(blank=True, null=True, verbose_name='Технический лог выполнения'),
        ),
        migrations.AddField(
            model_name='task',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время изменения статуса'),
        ),
    ]
