# Generated by Django 6.0.6 on 2026-09-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0009_task_execution_log_task_status_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='periodicity_unit',
            field=models.CharField(choices=[('none', 'Не повторять'), ('minutes', 'мин'), ('hours', 'ЧЧ'), ('days', 'ДД'), ('weeks', 'Н'), ('months', 'ММ'), ('years', 'ГГ')], default='none', max_length=10, verbose_name='Единица времени'),
        ),
    ]
