# Generated by Django 6.0.6 on 2026-09-12 21:39

from django.db import migrations


def update_null_values(apps, schema_editor):
    """Обновляет NULL значения на пустые строки для строковых полей."""
    Task = apps.get_model('daily', 'Task')
    Task.objects.filter(comment__isnull=True).update(comment='')
    Task.objects.filter(execution_log__isnull=True).update(execution_log='')


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0010_alter_task_periodicity_unit'),
    ]

    operations = [
        migrations.RunPython(update_null_values, migrations.RunPython.noop),
    ]
